### ISSUE TITLE
From Dust is missing the first mod

### ISSUE THREAD

**Issue by McFrugal** [LocalIdentity/PathOfBuilding#100]
The jewel only has the skeleton cooldown mod on it.  The first mod should be "Summon 4 additional Skeleton Warriors with Summon Skeleton".  For some reason, trying to paste in the full item data results in the parser missing that first mod, the only way it works is if you edit in the line manually afterwards.

**Comment by pHiney** [comment]
The code is not reading all the modlines/modlist

modlines = { {
  extra = " second to Summon<two spaces>Cooldown ",
  line = "+1 second to Summon Skeleton Cooldown",
  modlist = {}
  } }

original text (jewel.lua).
[[
From Dust
Cobalt Jewel
Limited to: 1
Variant: Pre 3.8.0
Variant: Current
{variant:1}Summon 2 additional Skeleton Warriors with Summon Skeleton
{variant:2}Summon 4 additional Skeleton Warriors with Summon Skeleton
+1 second to Summon Skeleton Cooldown
]]

If we place another variant in (for testing), eg: "{variant:2}Gain 30 Mana per Grand Spectrum"
then that variant will be shown.
So it appears to be the way the code is processing the text for the variant.
X

**Comment by ppoelzl** [comment]
Will be fixed in #138

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.2
