### ISSUE TITLE
Brutality Support does not factor in quality properly

### ISSUE THREAD

**Issue by landshark666** [LocalIdentity/PathOfBuilding#101]
As quality goes up for the Brutality Support skill gem, an extra physical damage increase is supposed to occur. Right now adding quality does nothing.

**Comment by LocalIdentity** [comment]
Can you please provide a Pastebin for the build that does not show the Brutality quality working. I just tested it myself and it seems to be working fine

**Comment by landshark666** [comment]
I tried again today and it worked, I'm not sure what was different about 1 week ago.
