### ISSUE TITLE
Brutality w/ Awakened Chaos vs Empowered

### ISSUE THREAD

**Issue by toddf2p** [LocalIdentity/PathOfBuilding#102]
https://pastebin.com/3XV4NkgX

Unless I'm missing something, awakened chaos shouldnt be stronger than empowered

**Comment by ppoelzl** [comment]
At least for me, it is not. Assuming that the respective gem would go into your main Spectral Throw setup, since your build code does not include _either_ support gem.

**Comment by toddf2p** [comment]
https://i.imgur.com/Wxq9UUI.png

https://i.imgur.com/SvmOtID.png

https://i.imgur.com/ffNz9Fb.gifv

https://pastebin.com/behAv8Fa

Spectral Shield Throw

Hopefully I'm not being a derp.

**Comment by LocalIdentity** [comment]
This actually apart of another bug where awakened gems are being ordered by lvl 20 variants instead of lvl 5. If you put both gems into the build awakened chaos gives 3% dps increase and empower gives 6%
