### ISSUE TITLE
Push access

### ISSUE THREAD

**Issue by pHiney** [LocalIdentity/PathOfBuilding#106]
what is the procedure for getting push access to dev branch (CONTRIBUTING.md) ?

**Comment by Laurgrin** [comment]
I'd assume you just make a pull request instead of getting a direct write access.

**Comment by pHiney** [comment]
That gets the files down. Doesn't allow me to send the the changes files back up.

**Comment by LocalIdentity** [comment]
You submit a pull request against the main branch. After it has been reviewed to be free of issue, I will accept the request and include it in the next update

**Comment by pHiney** [comment]
At work i would push _my_ branch up to the server and make a PR against master or the sprint branch, as appropriate. But here you have asked to make the change into dev (or have i misunderstood ?).

The bit i don't get here is the push

---------------------------------------------------------------------
Peter@peter-nb MINGW64 /d/git/PathOfBuilding.CE (dev)
$ _git status_
On branch dev
Your branch is up to date with 'origin/dev'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Classes/ImportTab.lua

no changes added to commit (use "git add" and/or "git commit -a")

Peter@peter-nb MINGW64 /d/git/PathOfBuilding.CE (dev)
$ _git add ._
warning: LF will be replaced by CRLF in Classes/ImportTab.lua.
The file will have its original line endings in your working directory.

Peter@peter-nb MINGW64 /d/git/PathOfBuilding.CE (dev)
$ _git commit_
[dev 88a001b] expose gameAccounts array to be used in import build tab. works with new brand install (ie blank entries). Table is sorted alphabetically
 1 file changed, 34 insertions(+), 4 deletions(-)

Peter@peter-nb MINGW64 /d/git/PathOfBuilding.CE (dev)
$ git push
**remote: Permission to LocalIdentity/PathOfBuilding.git denied to pHiney.
fatal: unable to access 'https://github.com/LocalIdentity/PathOfBuilding.git/': The requested URL returned error: 403**

**Comment by Laurgrin** [comment]
Well you don't have write access to push directly to the master branch, or any branch for that matter. Just make a pull request.

**Comment by pHiney** [comment]
Thanks for all that, but what i really needed to know was that i had to fork this repo into my own login
https://help.github.com/en/github/getting-started-with-github/fork-a-repo

In future, this would be best to tell people. Maybe add it to Contributing.md ?

**Comment by ppoelzl** [comment]
@pHiney  I think it's reasonable to assume you are familiar with Github already and not the responsibility of the project to teach you that. A simple search on "how to contribute on github" would suffice.
