### ISSUE TITLE
Despair Calculation incorrect

### ISSUE THREAD

**Issue by Seiyashi** [LocalIdentity/PathOfBuilding#110]
In a Bane - Despair - Enfeeble setup, Despair's added damage is listed at 15-19 (i.e. lv 5 values) despite being set to lv20. Removing/re-adding Bane or Despair does not resolve the issue.

**Comment by ppoelzl** [comment]
Interesting that it's lvl 5 specifically. Maybe that has something to do with the recent changes to support Awakened Gems?

**Comment by Seiyashi** [comment]
I deleted the entire old Bane group, set support gems to Non-awakened, and re-added Despair. Still seeing the lv5 values on Despair.

Build code: https://pastebin.com/0Er9gtuR (same as the Minion Life one)

**Comment by Seiyashi** [comment]
I tried inserting Despair into other existing save files that I have (predating 3.9), and the values show up correctly. Opened a new file and also saw correct values. As my build code is also the subject of another bug, I would not rule out the possibility of my .xml being corrupted.

**Comment by LocalIdentity** [comment]
The lvl 5 values are most likely the cause of a corrupted save from when there was a bug early on for this league where PoB was defaulting all gems to level 5 when you opened it. Can you verify if the bug persists if you reimport the character on a new save?

**Comment by Seiyashi** [comment]
I've just figured out the cause of the bug. Shaper/Elder option was set in Bosses, so the Despair values were scaled according to their reduced curse effect.
