### ISSUE TITLE
Minion Life Bug

### ISSUE THREAD

**Issue by Seiyashi** [LocalIdentity/PathOfBuilding#111]
On removing minion life nodes except Lord of the Dead, one 15% minion life node remains selected, despite verification that no more minion life nodes are selected.

**Comment by ppoelzl** [comment]
I cannot reproduce this. Would you provide a build code to test against?

**Comment by Seiyashi** [comment]
https://pastebin.com/0Er9gtuR

**Comment by LocalIdentity** [comment]
The increased minion life is coming from the quality of your minion life gem linked to your skeletons. https://pathofexile.gamepedia.com/Minion_Life_Support
