### ISSUE TITLE
Unnatural Instinct Jewel allocating a dex node when it shouldn't

### ISSUE THREAD

**Issue by pdr99** [LocalIdentity/PathOfBuilding#119]
![pob](https://user-images.githubusercontent.com/59712732/72112516-63169700-3370-11ea-8f33-64a67597dbb0.png)

**Comment by pHiney** [comment]
I don't see it. I started an empty build, went to the scion area of the tree where your picture shows it.
Scion DEX is 20. Added jewel and Dex went up to 25, which is correct.

P
