### ISSUE TITLE
Typo (Ailment Calc)

### ISSUE THREAD

**Issue by moppr** [LocalIdentity/PathOfBuilding#124]
> Ailment Threshold is about equal to Life except on bosses where is is about half of their life

should say

> Ailment Threshold is about equal to Life except on bosses where it is about half of their life

**Comment by LocalIdentity** [comment]
I wish I knew how to spell correctly. Thanks for letting me know

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.2
