### ISSUE TITLE
Support for Thread of Hope Jewel (or in general allocate nodes without path)

### ISSUE THREAD

**Issue by daish0** [LocalIdentity/PathOfBuilding#126]
Basically a feature missing for the new Thread of Hope Jewel, so we can allocate nodes based on it's new radius sizes - or just allow us to allocate nodes without path in general by using some hotkey.

Thanks

**Comment by LocalIdentity** [comment]
I had a look into implementing this and it seems quite simple from what I could tell, just need to make the code that applies to Intuitive leap but instead have it read the radius labels from the thread of hope jewels to apply the point allocation field to them

**Comment by daish0** [comment]
Hope it is easy, what I saw while messing with Intuitive Leap jewel as workaround, it doesn't really check the radius that is given in the item data but seems to be hardcoded to small radius.

A very simple workaround in general for items like this would be to have the possibility to simply freely allocate passive points on the tree without having the need of a connection.

**Comment by LocalIdentity** [comment]
Added in 1.4.157.2
