### ISSUE TITLE
Nearby Enemies have -9% to X Resistance bug

### ISSUE THREAD

**Issue by moppr** [LocalIdentity/PathOfBuilding#128]
In game, this mod only has one line, "Nearby Enemies have -9% to X Resistance." However, the auto-generated mod list from GGG somehow has another line, "-9% to X Resistance," which PoB interprets as applying to the player. This is picked up by anything using that data, including PoB and even PoEDB, despite not existing in game. On top of this, when PoB sees this false -9% affix, it flips all resistances of that element on the item to negative. For example, having a +40% to Cold Resistance affix in combination with the Nearby Enemies have -9% to Cold Resistance and erroneous -9% to (player) Cold Resistance actually results in the item having -49% to Cold Resistance. The item can be manually edited to its intended value as a workaround.

**Comment by moppr** [comment]
The offending mod from https://raw.githubusercontent.com/LocalIdentity/PathOfBuilding/master/Data/3_0/ModItem.lua

> ["DelveHelmetEnemyColdResistanceAura1"] = { type = "Suffix", affix = "of the Underground", "-9% to Cold Resistance", "Nearby Enemies have -9% to Cold Resistance", statOrderKey = "883,4584", statOrder = { 883, 4584 }, level = 1, group = "LocalDisplayNearbyEnemyColdDamageResistance", weightKey = { "abyss_jewel", "jewel", "helmet", "default", }, weightVal = { 0, 0, 2000, 0, }, },

**Comment by slicplaya** [comment]
Also, the "Nearby Enemies have -9% to X Resistance" calculates properly with Cold and Chaos damages respectfully; however, it does not work with Lightning or Fire resistances.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.2
