### ISSUE TITLE
Elemancer increased damage per summon golem not being calculated

### ISSUE THREAD

**Issue by Halffin** [LocalIdentity/PathOfBuilding#13]
![Screenshot (172)](https://user-images.githubusercontent.com/58403342/69920798-09ea4800-1441-11ea-9d87-3c7fc357494f.png)
as you can see in this screen shot the damage from Liege of the Primordial is being calculated correctly (thank you for that by the way!). I tried a new tree to see if it was just that specific tree was bricked, however the bug is easily reproducible by allocating the both Liege and Elemancer aswell as some golems.

**Comment by Halffin** [comment]
I dont know if it is relevant but the buff effect per summoned golem of elemancer seems to be working correctly

**Comment by LocalIdentity** [comment]
Elemancer : 20% increased Golem Damage per Summoned Golem
Liege of the Primordial: 20% Increased Damage per Summoned Golem
The elemancer node only applies to golem damage
