### ISSUE TITLE
(suggestion) Search crafting modifiers

### ISSUE THREAD

**Issue by Hapseleg** [LocalIdentity/PathOfBuilding#130]
Hi there, first of all holy f the added features are bloody amazing! Good job!

So my suggestion is that you add a search feature in the crafting bench such as this:

(quick and dirty edit)
![image](https://user-images.githubusercontent.com/12915302/72663738-285ad180-39f6-11ea-8d0f-12730e4abb96.png)

I've tried messing about with it, but I never tried working with lua before :)

Keep up the great work!

**Comment by Fish013** [comment]
I am currently working on a general search feature for dropdown lists. It is beeing tested right now.
Pull request will follow soon
![dropdown_search](https://user-images.githubusercontent.com/326399/72803406-50dd0880-3c4e-11ea-9e0f-6055732550d7.gif)
