### ISSUE TITLE
Badge of the Brotherhood and Brand Recall

### ISSUE THREAD

**Issue by ShanKanis** [LocalIdentity/PathOfBuilding#134]
Badge of the Brotherhood gives increased cooldown recovery per frenzy charge to travel skills. In PoB it seems to mistakenly count Brand Recall as a travel skill and apply that cooldown recovery to it. And just to confirm - in game Brand Recall does not count as travel skill, and cooldown reduction from badge is not applied to it.

**Comment by LocalIdentity** [comment]
Just fixed this for the next update

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.2
