### ISSUE TITLE
Vulconus avatar of fire stays enabled

### ISSUE THREAD

**Issue by Hapseleg** [LocalIdentity/PathOfBuilding#139]
If you equip Vulconus, enable "Do you have Avatar of Fire?" in configuration and unequip the weapon again, avatar of fire will stay enabled.

1. Equip Vulconus (unique dagger)
2. Enable "Do you have Avatar of Fire?" under configuration
3. Unequip Vulconus

Keep up the awesome work

**Comment by Fish013** [comment]
Related to #105

**Comment by LocalIdentity** [comment]
Duplicate of https://github.com/LocalIdentity/PathOfBuilding/issues/105
