### ISSUE TITLE
Arithmetic on a nil value error in CalcOffense

### ISSUE THREAD

**Issue by MrPing1000** [LocalIdentity/PathOfBuilding#14]
New update his made it so I can't import my spectral shield throw character, get the same error message.  I also cannot open a copied spectral shield throw build either.  

![PobError](https://user-images.githubusercontent.com/28328223/69923093-e0a9d600-1499-11ea-8a71-ef6aed837c6c.png)

**Comment by dragbone** [comment]
I can confirm this issue, steps to reproduce:
1. Equip Spectral Shield Throw
2. Link Impale Support or allocate any passive with 'chance to Impale'
3. Hover over any shield item

**Comment by LocalIdentity** [comment]
Fixed in 1.4.152.7
