### ISSUE TITLE
Arborix "30% more Damage" mod broken

### ISSUE THREAD

**Issue by H4xoltl** [LocalIdentity/PathOfBuilding#162]
So the bow has this mod;
"30% more Damage with Arrow Hits at Close Range while you have Iron Reflexes"

The mod is blue which suggests PoB knows how to parse it. However if you set a projectile travel distance of 1 and have allocated Iron Reflexes damage does not increase.

Contrast to Point Blank & Chin Sol which do work

Thanks for the hard work, lads.

**Comment by LocalIdentity** [comment]
Chin Sol and Arborix's mods only work if you check the "Is the Enemy at Close Range" box. While Point Blank works from the "Projectile Travel Distance" box
