### ISSUE TITLE
+max ballista totem on certain items and skill tree nodes arent properly implemented

### ISSUE THREAD

**Issue by Amountstax** [LocalIdentity/PathOfBuilding#165]
![Untitled](https://user-images.githubusercontent.com/60943070/74275567-16f9a200-4ce2-11ea-964c-0be7ad64036a.png)
Not working
- Ballista Totem Support
- Skirmish (Unique Quiver)
- Panopticon (Notable Passive)
- Watchtowers (Notable Passive)

Working
+ Multiple Totem Support
+ Pursuit of Faith (Templar/Hierophant)
+ Ancestral Bond (Keystone Passive)
+ Tukohama's Fortress (Unique Shield)
+ Shaper Shield (Rare Shield)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.5
