### ISSUE TITLE
Socketed Skill Gems Get A 90% Mana Multiplier not working for auras

### ISSUE THREAD

**Issue by Amountstax** [LocalIdentity/PathOfBuilding#169]
The Helmet corruption
"Socketed Skill Gems Get A 90% Mana Multiplier", isnt working for auras.

Seems to be working fine for other skills.

**Comment by ppoelzl** [comment]
The modifier you refer to reduces mana _cost_, not mana _reservation_, which are different, independent concepts: https://pathofexile.gamepedia.com/Mana_reservation. Please test your assuptions in-game or read up on game mechanics on the wiki before submitting bug reports. Should be closed.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.5
