### ISSUE TITLE
The formless Inferno's text is wrong

### ISSUE THREAD

**Issue by Hapseleg** [LocalIdentity/PathOfBuilding#181]
"The formless inferno" in POB says "8% of Physical Damage taken as Fire Damage" but it should say "8% of Physical Damage **from Hits** taken as Fire Damage".

Not sure if theres more errors than just this case?

Keep up the good job

**Comment by Hapseleg** [comment]
Cane of Unravelling has an extra space in its implicit "18% Chance to Block  Attack Damage while wielding a Staff"
Maybe pull the items from another source? I am guessing you are doing the changes yourself? https://github.com/brather1ng/RePoE has all the uniques I think.

**Comment by NickRyder** [comment]
@Hapseleg Please make separate issues for separate problems.

`RePoE` does not contain information about the uniques directly, since ggg pulled the info out of the `ggpk` awhile ago. However, it does contain implicits for base items.

**Comment by Hapseleg** [comment]
Sorry, will do

**Comment by ppoelzl** [comment]
@Hapseleg As a consequence, even if we were to pull from another source, someone would eventually have to type in the unique by hand. There is no way to remove all manual errors because of this.

**Comment by Hapseleg** [comment]
Ah I thought they pulled it from an api or something like that

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.5
