### ISSUE TITLE
Some configuration options don't work

### ISSUE THREAD

**Issue by PJacek** [LocalIdentity/PathOfBuilding#194]
There are multiple skill specific options in the configuration tab that don't work:
- blade count for spectres' Blade Vortex
- spectres' curses
- Ursa's Rallying Cry
- Holy Relic's Aura
- Lightning Golem's Aura

[Pastebin](https://pastebin.com/jepUNjRm)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.5
