### ISSUE TITLE
Unrecognized unique affix on Darkscorn bow.

### ISSUE THREAD

**Issue by gwarlek** [LocalIdentity/PathOfBuilding#2]
"20% chance for Poisons inflicted with this Weapon to deal 300% more Damage" this wording doesn't work.
I have to change it to this manually "Poisons you inflict during any Flask Effect have 20% chance to deal 300% more damage" for it to take effect.

**Comment by LocalIdentity** [comment]
This mod works perfectly fine for me, can you please link the Pastebin for the build you're using so I can make sure

**Comment by LocalIdentity** [comment]
Fixed in 1.4.152.6
