### ISSUE TITLE
Active Totem Limit not independently calculated

### ISSUE THREAD

**Issue by meatballing** [LocalIdentity/PathOfBuilding#206]
Active totem limit is only calculated based off one skill, meaning that if you had multiple skills with different active totem limits, only one of the skills with have the correct value.

**Repro**
1. Create skill with Fireball - Spell Totem
2. Create skill with Freeze Pulse - Spell Totem - Multiple Totems Support

Both skills show active totem limit as 3 when Fireball should be 1.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.5
