### ISSUE TITLE
PoB crashing after recent update

### ISSUE THREAD

**Issue by DmytroKanivets** [LocalIdentity/PathOfBuilding#223]
![image](https://user-images.githubusercontent.com/15801478/75249051-17b02f00-57de-11ea-92bb-5c7eb8d8aade.png)

Enter closes error window and leaves on empty screen. Click on "Options" reproduces the error

**Comment by Alco67** [comment]
Same issue here

**Comment by ppoelzl** [comment]
@DmytroKanivets Is it fixed now?

**Comment by Alco67** [comment]
Fixed for me, thx
