### ISSUE TITLE
Bane is incorrectly counting an extra linked curse

### ISSUE THREAD

**Issue by tcbeutler** [LocalIdentity/PathOfBuilding#225]
Following the 1.4.157.7 update, when Bane is linked with 0 curses, the damage is computed correctly.

When a single curse is linked to Bane, the "More" multiplier shows 2 linked curses. As additional curses are linked, it carries the 1 extra curse forward, presumably from Bane itself.

Example PoB: https://pastebin.com/kc2EL0P0

"Total More" shows 90% for Bane at 45% per curse applied. This was correctly 45 in the previous version.

**Comment by PJacek** [comment]
This is caused by dcb5f1b4372675fa4152217d329b5cb2237a4718. The condition `AppliedByBane` gets copied and tests true for all active skills. Bane counts active skills in the same group that have this condition (up to curse limit). In this case it's Despair and self.

**Comment by LocalIdentity** [comment]
Reverted the rage fix until we have a more permanent solution
