### ISSUE TITLE
Tree highlighting options and Screen Resolution

### ISSUE THREAD

**Issue by AvengingAngel54** [LocalIdentity/PathOfBuilding#24]
Depending on your screen resolution you are not able to see/fully see the different highlighting options offered at the bottom right corner as most of the text will be off screen. https://imgur.com/a/cxFIHao (My resolution is 1366x768)
I'd personally recommend either shrinking the size of tree selector and search bar or adding an option so everyone can adjust it on their own.

Thanks and have a great day.

**Comment by LocalIdentity** [comment]
Will be fixed in 1.4.153.2
