### ISSUE TITLE
Gem issue

### ISSUE THREAD

**Issue by EurousTV** [LocalIdentity/PathOfBuilding#247]
https://i.imgur.com/zGdxNR0.png seems to be a problem with latest build for me, scrolling through gems this just pops up no matter what

**Comment by Regisle** [comment]
happens if you hover over bone armour, not sure if happens otherwise

**Comment by pHiney** [comment]
PR #242 seems to remove Bone Armour

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.7
