### ISSUE TITLE
Rage Support 10-stack bonus incorrectly gives damage to unarmed builds

### ISSUE THREAD

**Issue by Wbolin** [LocalIdentity/PathOfBuilding#25]
Recreate with:

Import https://pastebin.com/Fjsnwcan

See Calc Min added Phys

Toggle Rage Support on

Check Calc Min added phys having too large of a number. (+43 instead of +4)

**Comment by homutan** [comment]
Supported Attacks deal (2-39) to (4-72) added Physical Damage with Weapons while you have at least 10 Rage
Supported Attacks deal (1-4) to (2-7) added Physical Damage with Weapons per 10 Rage

4 per 10 rage + 39 if 10+ rage = 43
