### ISSUE TITLE
Rage doesn't grant movement speed

### ISSUE THREAD

**Issue by MatthewSbar** [LocalIdentity/PathOfBuilding#28]
Rage (from rage support) in the "when in combat" configs panel doesn't grant any movement speed.

**Comment by dragbone** [comment]
I tried to look into this but couldn't locate the bug. What I found is that rage from the Rage Support Gem and other skills (e.g. Chain Hook) don't grant defensive stats from rage (only the Berserker Ascendancy does). Somehow the calculation of defensive stats is different than offensive stats and the CanGainRage flag is not correctly set in the defensive calculation. I hope somebody else can find the bug with this information 😞
PS: I also tried adding some custom mods (%Armour per rage) and all defensive stats were only granted from the ascendancy and not from skills.

**Comment by notLiria** [comment]
Steps to reproduce this bug:
- Set Skills: Chain Hook 
- Set Items: Any weapon that Chain Hook works with
- Configuration: Add any non-zero number of Rage stacks; make sure Berserker points regarding Rage aren't allocated
- Go to Calculation tab, movement speed does not increase. 

Am taking a look at it now

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.5
