### ISSUE TITLE
Incorrect handling of skill data

### ISSUE THREAD

**Issue by PJacek** [LocalIdentity/PathOfBuilding#3]
I haven't checked all commits but I believe that at least part of the changes to skill data (and possibly other data too) has not been implemented correctly.
The files in `Data/3_0/Skills` should be generated automatically from template files in `Export/Skills` (as instructed in [CONTRIBUTING.md](https://github.com/LocalIdentity/PathOfBuilding/blob/master/CONTRIBUTING.md)). It's done by the scripts located in `Export/Scripts`. Specifically calling this function: https://github.com/LocalIdentity/PathOfBuilding/blob/6229502a9c637bcf74696c1bffc472e841c8904a/Export/Main.lua#L92 from https://github.com/LocalIdentity/PathOfBuilding/blob/6229502a9c637bcf74696c1bffc472e841c8904a/Export/Scripts/skills.lua#L355 handles the skill data.
The current changes to wither and elusive are incorrectly implemented in the generated `.lua` files and using the export functionality is going to erase them.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.152.6
