### ISSUE TITLE
Equipping Drillneck erroneously gives Toxic Rain a 50% increased damage mod

### ISSUE THREAD

**Issue by ogier** [LocalIdentity/PathOfBuilding#31]
In PoB, equipping Drillneck increases the DoT damage of Toxic Rain, and you can see in the calcs tab it is coming from Drillneck's modifier reading "Arrows deal 50% increased Damage with Hits and Ailments to Targets they Pierce".

But Toxic Rain's DoT is neither a Hit nor an Ailment. In-game, equipping Drillneck does not change the "Deals X Chaos Damage per second" part of Toxic Rain's tooltip at all.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.153.1
