### ISSUE TITLE
 Source Name incorrect for Skill Gem AoE

### ISSUE THREAD

**Issue by damonkman** [LocalIdentity/PathOfBuilding#32]
This is purely a visual issue from what I can tell, all the math is accurate just the labels. This is when you mouse over the "Area of Effect Mod" under "Skill type-specific Stats"

All auras give the Source Name for increase to AoE from quality to the name "Precision" regardless of which aura you look at. For skills that get 0.5% AoE per quality the source is always listed as "Cyclone" regardless if your actual skill is Ice Nova or Blade Vortex for example. I also checked the original Path of Building branch and this is local to this fork. Just something I noticed so thought I would report it.

**Comment by dragbone** [comment]
Just tested this with Wrath and Ice Nova and both show AoE increases from quality correctly. Could you try this again with the current version of this fork?

**Comment by damonkman** [comment]
Yeah its fixed now.
