### ISSUE TITLE
Can you add "pastebinp.com" proxy as an import option?

### ISSUE THREAD

**Issue by Fogo0** [LocalIdentity/PathOfBuilding#3252]
### Check for duplicates

- [x] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

In my country(Turkey) pastebin.com is banned by government. I am forced to use a pastebin proxy called "pastebinp.com".
It would be great to use that site as a import option in the PoB client.

### Describe the solution you'd like

pastebinp.com as an import option for the PoB client.

**Comment by MaxKruse** [comment]
@Fogo0 this should be solved in the next release.
