### ISSUE TITLE
Cold snap/flicker strike cooldown bypass

### ISSUE THREAD

**Issue by RomainMaucci** [LocalIdentity/PathOfBuilding#3263]
Can you add a feature to override the cold snap cooldown when using a frenzy or a power charge ?

I think it can be done for flicker strike too

Thanks for your amazing work

**Comment by RomainMaucci** [comment]
The cooldown change the cast rate and the cast rate interact with the DPS ?

With 3.00s of cooldown on Cold Snap my cast rate is 0,67 but in reality if there is no cooldown it is much higher

Tell me if i'm wrong

**Comment by Lilylicious** [comment]
You are not wrong! I was just looking at flicker strike, where the cooldown does not seem to matter. Cold snap does respect the cooldown.

Should have a PR up soon.
