### ISSUE TITLE
in "OnFrame" : not enough memory

### ISSUE THREAD

**Issue by stubbze** [LocalIdentity/PathOfBuilding#3377]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

builds should open

### What is the actual behaviour/value?

when opening builds 3.15 and below

### How to reproduce the issue

try to open try to open build 3.15 or lower

### Build code

```shell
i dont know, look screenshoot
```

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/34101164/137807518-d04ad08b-f728-4e82-a2b7-e055d1eb5e14.png)

**Comment by tavise** [comment]
I have the same issue.  Attempting to open an older build.  Opened fine on the previous version.

**Comment by Hasanderson** [comment]
I have the same problem with my buildss I can't open it and convert new tree to see it.
![Безымянныйs](https://user-images.githubusercontent.com/92761157/137813247-34ec1073-984d-4670-b728-fc2989cb8663.jpg)

**Comment by nimama8011** [comment]
apparently some are able to load while some other are not. Hopefully the fix will be released soon
