### ISSUE TITLE
Lethality doesn't apply to "rain" attack projectiles

### ISSUE THREAD

**Issue by Souchy** [LocalIdentity/PathOfBuilding#3452]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

"Projectile Attack Skills" modifiers from the "Lethality" wheel should affect all rain projectile attack skills like Rain of Arrows and Artillery Ballista.

Examples mods:

- "Projectile Attack Skills have 50% increased Critical Strike Chance"
- "Projectile Attack Skills have +30% to Critical Strike Multiplier"

### What is the actual behaviour/value?

Those mods currently do not apply to rain-type projectile attack skills like :
- Rain of Arrows 
- Vaal Rain of Arrows
- Artillery Ballista
- Blast Rain
- Toxic Rain
- Storm Rain

These skills properly work with "Projectile" and "Attack" nodes as they have both tags. 
Edit: They also work well with "Projectile Attack Hits" from Point Blank and Far Shot.

The Lethality mods currently properly work with other projectile attacks like Lightning Arrow, even when supported by Arrow Nova.

### How to reproduce the issue

Run Updated 2.10.0 Pob Community Fork
Select Rain of Arrows as main skill
Equip a bow
Allocate Lethality

### Build code

```shell
https://pastebin.com/CtubMddJ
```

**Comment by ever1309** [comment]
> Doesn't work in game either so nevermind. Although GGG didn't say anything about it afaik.

it works in game now, but pob still not updated.

**Comment by Lothrik** [comment]
This is fixed by #3851 (which is already merged to ``dev``), you'll see the change in 2.14.0 in the next week or so.

**Comment by ever1309** [comment]
> This is fixed by #3851 (which is already merged to `dev`), you'll see the change in 2.14.0 in the next week or so.
good to know, thanks!
