### ISSUE TITLE
Choosen Mastery don't get saved if export and import tree

### ISSUE THREAD

**Issue by Odin099** [LocalIdentity/PathOfBuilding#3534]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

export a tree and import it to a new tree don't save the choosen mastery

### What is the actual behaviour/value?

export a tree and import it to a new tree don't save the choosen mastery

### How to reproduce the issue

just select any Mastery then export the tree and import it to a new tree

### Build code

```shell
https://www.pathofexile.com/passive-skill-tree/3.16.0/AAAABAMBAESrNsUsnNgku_a86mpDhndlcm0Zj6ZVrgj037BWSIIQCwwRLR8C
```

**Comment by QuickStick123** [comment]
I can't replicate this on the latest version 2.10 the supplied tree seems to import fine. And still works fine upon export and import.
![tree](https://user-images.githubusercontent.com/31533893/138378135-ab576c22-535c-4ccb-a263-226debe70615.PNG)
