### ISSUE TITLE
Sapped not having a Window to select its strengh on enemies

### ISSUE THREAD

**Issue by IceMagma** [LocalIdentity/PathOfBuilding#3578]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When the option for Sapped is ticked in Configurations you should get a window to determine the amount of Sapped on the enemy

### What is the actual behaviour/value?

There is no such window

### How to reproduce the issue

Equip the Interogation cluster jewel and skill into Secrets of Suffering afterwards tick Sapped in configuration

### Build code

```shell
https://pastebin.com/t7sskDdc
```

**Comment by Lothrik** [comment]
Alternate ailments (Sap, Brittle, and Scorch) all work correctly as of 2.18.1 (Sap even affects enemy damage dealt now) and have input boxes to select their magnitude. Tested with The Interrogation equipped and Secrets of Suffering allocated.
