### ISSUE TITLE
Node Power options don't respect Color Choice

### ISSUE THREAD

**Issue by moehrd** [LocalIdentity/PathOfBuilding#36]
In options is a drop down for Node power colors, it is expected that all options in the drop down respect this color choice (i would assume the first choice being increases and the second being decreases) 

However, only the Offence/Defence option uses either color, and all the other Node Power options use the OTHER color (e.g. if i choose Red & Blue, for all non-"Offence/Defence" choices, all nodes will be highlighted in shades of Green)

I choose Red & Green because Blue is hard for me to see, and this means that if i want to use any of the other Node Power filters, i need to change my colour setting, and then back again to use Offence/Defence.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.153.2
