### ISSUE TITLE
"Master of Metal" added damage not working

### ISSUE THREAD

**Issue by hgfedcba** [LocalIdentity/PathOfBuilding#39]
The added damage component of "Master of Metal" is highlighted as working, but it doesn't. See https://pastebin.com/hxzgCWnj

**Comment by LocalIdentity** [comment]
The Master of Metal node does work, you need to set the number of Impales on the enemy for it to work at the moment

**Comment by hgfedcba** [comment]
I didn't know "Master of Metal" works if you insert the in "#of Impales on Enemy (if not maximum)", but the wording really suggests that you do not need to enter the number of your maximum impales to have pob use it.

I also don't quite understand why this is necessary, since the number of your impales is acurately tracked in pob...
