### ISSUE TITLE
Screen resolution problem

### ISSUE THREAD

**Issue by PauloCesarSchunke** [LocalIdentity/PathOfBuilding#4179]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Hello, I have this new monitor but its resolution is 1360x768 60Hz.
So a part of the screen is missing, and I would like to know if there is a way to solve this problem.

### What is the actual behaviour/value?

Hello, I have this new monitor but its resolution is 1360x768 60Hz.
So a part of the screen is missing, and I would like to know if there is a way to solve this problem.

### How to reproduce the issue

Just opem app

### Build code

```shell
https://pastebin.com/iPJQCnZB
```

### Screenshots
Full screen
![tela 1](https://user-images.githubusercontent.com/99917979/154566214-531ad8c7-1ab4-4bef-b954-805fddd66fb3.jpg)
My resolution
![tela 2](https://user-images.githubusercontent.com/99917979/154566244-cc47ed15-f9de-4505-80c4-f2989e076dc8.jpg)

**Comment by pHiney** [comment]
There is a minimum height and width of the application. I am investigating what those values are.

**Comment by guivc** [comment]
As far as I know of most laptops sold in Brazil have this as maximum resolution.

I'm having the same UI too!

**Comment by Punter2022** [comment]
@Wires77
Sorry but that didn't work here.

**Comment by Wires77** [comment]
> @Wires77
> Sorry but that didn't work here.

The fix hasn't been released yet.  This issue will close itself when the fix is in the dev branch, and a beta release will come shortly after
