### ISSUE TITLE
Everything highlights on mouse-over even when the PoB window isn't in focus.

### ISSUE THREAD

**Issue by NGTagger** [LocalIdentity/PathOfBuilding#43]
Been trying to get Openarl's attention with this, but it's apparently such a small matter that he keeps on ignoring it..

![](https://i.imgur.com/R7FXSb8.png)
See how the cursor is on another window (in this case; Chrome - even though that's not clearly shown, I know), while still highlighting things from PoB behind the window that's in focus.
This happens no matter what window is on top or even if I place 5 windows on top of PoB. PoB just doesn't care.

It would be awesome if this fork could actually fix this issue.

**Comment by dragbone** [comment]
This might be impossible for this fork. Some of the PoB features are not open source, mainly the launcher and the core parts for rendering/UI. As I see it, this would require the core UI to expose some information about the window (if it's active & on top) which it currently doesn't. Would love to see this implemented but imho it's not possible at the moment.

**Comment by ppoelzl** [comment]
Actually almost impossible, any rendering changes are off-limits unless rendering is reimplemented.

**Comment by NGTagger** [comment]
Well that sucks, seeing as Openarl obviously never wants to change this.
Was hoping it was doable here. Oh well..
