### ISSUE TITLE
Uniques affecting Bleed DPS - Feature Request

### ISSUE THREAD

**Issue by DangerDmillz** [LocalIdentity/PathOfBuilding#46]
Lion's Roar and Ryslatha's coil should both affect bleed but do not change the Bleed DPS.

**Comment by cfepes** [comment]
Lion's Roar behavior is correct. Melee Physical Damage% does not affect bleed. However Ryslatha's Coil should be affecting bleed damage and is not.

**Comment by DangerDmillz** [comment]
Interesting, I just assumed it applied to the base damage but good to know thanks!

**Comment by cfepes** [comment]
Its easiest to see on Melee Physical Damage Support. Its why it has both of these mods:
* Supported Skills deal 49% more Melee Physical Damage
* Supported Skills deal 49% more Damage with Bleeding and Poison caused by Melee Hits

**Comment by dragbone** [comment]
Ryslatha's Coil gives 'Physical **Attack** Damage' which shouldn't scale bleed as far as I know. For example the unique Jewel Warlords Reach provides '8% increased Attack Damage' and that doesn't scale bleed dps as well.
The added physical damage on Ryslatha's Coil should and does increase the bleed dsp.
