### ISSUE TITLE
Xoph's Nurture duplicate modifier

### ISSUE THREAD

**Issue by custompro12** [LocalIdentity/PathOfBuilding#48]
Xoph's Nurture Citadel Bow has two mods that say:

> Socketed Gems are Supported by Level 20 Ignite Proliferation
> Socketed Gems are Supported by level 20 Ignite Proliferation

*Also, note the difference in capitalization of 'level'

![image](https://user-images.githubusercontent.com/12768953/70683321-f70d1a00-1c6f-11ea-9a10-dcfbfd57db53.png)

**Comment by LocalIdentity** [comment]
Will be added in 1.4.153.2
