### ISSUE TITLE
Window scaling problem

### ISSUE THREAD

**Issue by randomguysomewhere** [LocalIdentity/PathOfBuilding#55]
No matter how much I scale the window I can't make it to fully show the "Show Node Power" button (same at full window).  https://i.imgur.com/iaa2uVv.png

**Comment by dragbone** [comment]
What resolution is your display? I think you need at least FullHD to display everything. Also check if you have display scaling turned on, that tends to mess with things.

**Comment by LocalIdentity** [comment]
Will be fixed in 1.4.153.2
