### ISSUE TITLE
survivalist flat evasion not working

### ISSUE THREAD

**Issue by hgfedcba** [LocalIdentity/PathOfBuilding#56]
In this patebin I skilled survivalist with +3% chance to evade attacks and have 0% chance to evade attacks
https://pastebin.com/7j54WBQR

**Comment by ppoelzl** [comment]
I cannot reproduce this, maybe you should reinstall PoB.

**Comment by veenarm** [comment]
I imported in 1.4.153.1 and it shows 40% evade with 36% from tree.
