### ISSUE TITLE
Update Failed - newest build broken?

### ISSUE THREAD

**Issue by Gladaed** [LocalIdentity/PathOfBuilding#60]
When trying to update PoB says update check failed. This happens after the last of the downloads, which start during the check. This might be related to the new build that was just pushed. 

Possible source: i manually updated to the new tree on wensday, but patched afterwards to the most current version.

**Comment by ninox14** [comment]
same

**Comment by UniQueKakarot** [comment]
Got the same issue on my part, update check failed.

**Comment by mfukar** [comment]
Had the same issue - PoB complained for a checksum mismatch for `TreeData/3_9/tree.lua`. After a few retries the update succeeded for me, so it may be an intermittent or environmental issue.

**Comment by niklaas-0rbit** [comment]
Had the same issue, seems solved? Was able to successfully update now to version 1.4.153.2

**Comment by Gladaed** [comment]
Fixed
