### ISSUE TITLE
How can "Path of Building.exe" be built from scratch?

### ISSUE THREAD

**Issue by MoldyDwarfPoE** [LocalIdentity/PathOfBuilding#62]
According to CONTRIBUTING.md, developers are required to use the pre-built .exe file to run PoB. Is there source available for it? How can the .exe and .dlls be built from scratch?

**Comment by LocalIdentity** [comment]
You have to use the .exe of your normal PoB installation. It's usually in C:\Program Files (x86)\Path of Building
