### ISSUE TITLE
Outdated Passive Tree Anointment Oils  

### ISSUE THREAD

**Issue by BrettDuclos** [LocalIdentity/PathOfBuilding#63]
It appears with the new tree, there have been updates to the required oils for anointment. I am uncertain how many notables have been affected, but a spot check of a handful indicated most have been changed in some way.

**Comment by NickRyder** [comment]
Could you please give examples of this for us to investigate?

**Comment by BrettDuclos** [comment]
Avatar of the Hunt says Clear Teal Teal, while it is now Clear Opalescent Opalescent. 
Clear Teal Teal now gives Saboteur, which used to require Sepia Violet Golden.

[This spreadhseet](https://docs.google.com/spreadsheets/d/1zBKRD2fqNtPS59PXM1oc_RaFrszqdrrr2BEYhrquKPQ/edit#gid=0) appears to have updated values for all of the ones that I checked. I think it is safe to say that all of them have been rearranged.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.155.1
