### ISSUE TITLE
The Red Nightmare jewel block chance calculation not working

### ISSUE THREAD

**Issue by jtt331** [LocalIdentity/PathOfBuilding#64]
My build
https://pastebin.com/NyEVCj11

My Red Nightmare jewel is in Jewel socket #1 (near Marauder area) - if you add/remove the Red Nightmare jewel, there is no difference in the block chance (60%)
Even in the Calcs window, the Red Nightmare is not shown in the block chance calculations.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.1
