### ISSUE TITLE
Copying items into PoB not working correctly.

### ISSUE THREAD

**Issue by ShanKanis** [LocalIdentity/PathOfBuilding#65]
When using ctrl + c on item in game and then copying the item into PoB the item copies properly except for implicit. Copied Item's implicit have added (implicit) after it, which prevents PoB from reading the stat. Attaching crop from PoB to better explain what I mean.
![Implicit Bug](https://user-images.githubusercontent.com/7843174/70866312-5fa61080-1f68-11ea-8e3a-d633d4081e51.png)

To clarify - removing (implicit) in edit mode makes it work properly.

**Comment by LocalIdentity** [comment]
This is something they added in the 3.9, I'll fix it for the next update

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.1
