### ISSUE TITLE
Unable to save Empower/Enhance/Enlighten as Level 4

### ISSUE THREAD

**Issue by emrysduvent** [LocalIdentity/PathOfBuilding#68]
Can set the gem level to 4, but the level goes back to 3 on saving and reopening

**Comment by rcpd** [comment]
Same, only noticed it in the latest build but unsure how long it's been going on.

**Comment by emrysduvent** [comment]
I only saw it this build. Was fine before.

**Comment by Sectoidfodder** [comment]
Blood and Sand keeps resetting down to lvl 6 as well.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.1
