### ISSUE TITLE
1.4.155.1 'chanceOnCrit' Error -- Can't Load Build

### ISSUE THREAD

**Issue by azul1337** [LocalIdentity/PathOfBuilding#70]
After installing the recent update I can no longer load my build at all. This is the screenshot of the error:

![image](https://user-images.githubusercontent.com/9420331/70887976-30fe5900-1fad-11ea-9a1d-07048bc586e2.png)

**Edit**: It seems I'm able to load every other build except the two that were open at the time of the update. I guess something broke during the process?

**Edit2**: It seems to stem from changing the "Calculation Mode" in Calcs to "In Combat." I was able to reproduce the error on other saved builds in this manner.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.1
