### ISSUE TITLE
New +1 gem modifiers not being calculated

### ISSUE THREAD

**Issue by xanthics** [LocalIdentity/PathOfBuilding#75]
![image](https://user-images.githubusercontent.com/3137623/71131569-e564ce80-21a9-11ea-8b4c-8c8fa2450ed6.png)

The new +1 all gems modifiers that can spawn on Amulets are not being calculated.  This is a Shockwave totem build with an aura active.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.1
