### ISSUE TITLE
update install instructions

### ISSUE THREAD

**Issue by i3igpete** [LocalIdentity/PathOfBuilding#76]
Openarl's manifest.xml was slightly shuffled around, and the PART attribute is now at the end of the string.  Not a huge issue, but for non-savvy users the line now appears as:

> Source url="https://raw.githubusercontent.com/LocalIdentity/PathOfBuilding/{branch}/" part="program"/

**Comment by LocalIdentity** [comment]
Just updated them to show both ways the manifest file can look
