### ISSUE TITLE
Is there a reason this is still a fork, and not a PR

### ISSUE THREAD

**Issue by stvndall** [LocalIdentity/PathOfBuilding#80]
As the Issue name asks, while not an actual issue with the code, but I would like to see these in the base version of pob, and it doesn't look like there is any reason why it can't be merged into the base PoB.

**Comment by NickRyder** [comment]
@stvndall This is an issue to take up with OpenArl, not LocalIdentity.

You will most likely find the same hesitance the rest of us have found.
