### ISSUE TITLE
Build code import: pasting into import text field not working on macos.

### ISSUE THREAD

**Issue by medienbaum** [LocalIdentity/PathOfBuilding#81]
Using CMD + V just inputs a "v" into the import code field. Nothin else is working. Neither Chrome nor Firefox work, Safari does not Support WebGL 2.0.

**Comment by ppoelzl** [comment]
Since you are mentioning browsers, I assume you use pob.party.
Please note that pob.party is unaffiliated with both Forks of the desktop version of Path of Building.
This issue can be closed.

**Comment by LocalIdentity** [comment]
PoB does not currently support MacOS
