### ISSUE TITLE
How can I interact with pob.party through the console ?

### ISSUE THREAD

**Issue by FrancoisMentec** [LocalIdentity/PathOfBuilding#82]
Hello,
I'd like to interact with pob.party through the console with a chrome extension. I'd like to be able to load a build from a code, get the dps from a skill, change an item, etc. Is it possible? Is there an API documentation somewhere?

**Comment by ppoelzl** [comment]
pob.party is not affiliated with Path of Building.

**Comment by FrancoisMentec** [comment]
Yeah, I realized that later. It's this GitHub that appears on their "about" page, apparently, they don't have their own GitHub.
