### ISSUE TITLE
Headless pob-code generation

### ISSUE THREAD

**Issue by ConaGo** [LocalIdentity/PathOfBuilding#8347]
I am writing here in lack of a better place to ask questions (If there is one please tell me:) )

Hi, i am trying to load in a build from json to then generate a pob-code from it via the HeadlessWrapper.lua

I've looked up the code from ImportTab.lua:176 which does the following

`common.base64.encode(Deflate(self.build:SaveDB("code"))):gsub("+","-"):gsub("/","_")`

But this of course always renders an empty string because the HeadlessWrapper.lua mocks the Deflate function

```
function Deflate(data)
	-- TODO: Might need this
	return ""
end
```

I can't find the Deflate function anywhere else in the project, so i would really appreciate any hints on how i can export the pob code.

I am currently in the process of automating the export of stats data into python and i would really love to get some guidance on how to get the most info out of POB, like ticking all flasks, selecting the correct skill etc.

I would in turn offer to collect and write down all my findings and add some usage examples into the HeadlessWrapper.lua if that's cool.

**Comment by Paliak** [comment]
Deflate is exported from SimpleGraphic which is the runtime POB uses:

https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/blob/50ea594d219cfe9fb303c4afa6ae7672da08c7d1/ui_api.cpp#L952-L991

POB codes are just deflated xml with b64 encoding ([CyberChef recipe](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9-_',true,false)Zlib_Inflate(0,0,'Adaptive',false,false)))

To load builds from json you should be able to use:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/78b52c95ec3f531abd8d6965e6e554e09f43a269/src/HeadlessWrapper.lua#L196C10-L203

For exporting you'll probably need to create the links yourself unless you want to modify [the headless wrapper a bit](https://github.com/Paliak/PathOfBuilding/blob/tests-branch/src/HeadlessWrapper.lua) though you'll probably need to [install more dependencies](https://github.com/Paliak/PathOfBuilding/blob/tests-branch/Dockerfile)

For modifying build state from the headless wrapper see files in spec/System/

I'll close this but feel free to comment or see [this](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/CONTRIBUTING.md#before-submitting-a-pull-request) to join the discord.

**Comment by Paliak** [comment]
Make sure you're using the url save b64 alphabet. You can see the implementation i had success with [here](https://github.com/Paliak/PathOfBuilding/blob/tests-branch/src/HeadlessWrapper.lua) and [here](https://github.com/Paliak/PathOfBuilding/blob/tests-branch/Dockerfile).

**Comment by ConaGo** [comment]
> Make sure you're using the url save b64 alphabet. You can see the implementation i had success with [here](https://github.com/Paliak/PathOfBuilding/blob/tests-branch/src/HeadlessWrapper.lua) and [here](https://github.com/Paliak/PathOfBuilding/blob/tests-branch/Dockerfile).

Thanks for the hint. I opted in to get the xml from PoB and did the rest in python :)

**Comment by ConaGo** [comment]
@Paliak  i would really like to join the Discord, but i don't know how to reach out to @LocalIdentity or @Wires77 except for here maybe?
If you see this please invite me. I am working on a tool that lets user see a history of their build progress interactively but to make it searchable i need to export more data from PoB about the main skills and damage. Preferably i am aiming for the data that poe.ninja is showing. 

I'd be really happy to have a chat about that :)

**Comment by Regisle** [comment]
This discord <https://discord.com/invite/pathofexile>
