### ISSUE TITLE
Concentrated Effect + Arctic Breath

### ISSUE THREAD

**Issue by tripngroove** [LocalIdentity/PathOfBuilding#84]
Conc Effect should increase DoT DPS for arctic breath, but does not.

Confirmed via in-game tooltip.

**Comment by LocalIdentity** [comment]
The in game tooltip does not reflect the DoT DPS, it shows the hit component of arctic breath which conc effect does work on. Conc effect does not increased DoTs for any skill

**Comment by tripngroove** [comment]
I think that's incorrect? In-game tooltip specifically shows that the DoT gets scaled:

![ArcticBreathDoTConcEffectvsUnsupported](https://user-images.githubusercontent.com/46039/72324246-54293080-365f-11ea-973d-79425c756dd1.png)

**Comment by tripngroove** [comment]
Also... I couldn't substantiate this claim, but I found a reddit thread discussing why the cold DoTs are different:

>Area damage applies to those skills because they deal damage over time only within their area of effect.
>Area damage doesn't apply to Soulrend, Bane, Contagion, Essence Drain, or Blight, because those skills only apply a damage over time debuff with a duration to enemies within their area of effect. So the area itself isn't dealing any damage - just the debuff is, and even if an enemy teleported away immediately after being afflicted it would take full damage from that debuff. Whereas with Cold Snap, Vortex, Arctic Breath, and Vaal Cold Snap, any enemy that leaves the area immediately stops taking damage.

**Comment by LocalIdentity** [comment]
Definitely an interesting interaction, wonder if people who play cold dogs kills know this or if it’s only been a recent addition

**Comment by LocalIdentity** [comment]
Will have to go though each cold dot skill to be sure then add that functionality into a new update

**Comment by LocalIdentity** [comment]
Fixed the bug, just needed to add one line to the spell to make the DoT work with conc effect, will be in the next update

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.2
