### ISSUE TITLE
Purifying Flame not a "Strength skill gem"

### ISSUE THREAD

**Issue by DangerDmillz** [LocalIdentity/PathOfBuilding#90]
+1 to Strength Skill Gems does not apply to Purifying Flame.

**Comment by ppoelzl** [comment]
Correct, as Purifying Flame is a Intelligence skill gem.
This issue can be closed.

**Comment by DangerDmillz** [comment]
Incorrect as I'm using a +3 to physical skill gems staff and it increases the level in game. Also you can clearly see that it requires Strength to use.

![image](https://user-images.githubusercontent.com/56979118/71988641-194d7580-31e5-11ea-9f68-3760c4885b9f.png)
