### ISSUE TITLE
Gem DPS sorting treats awakened gems at Lv20

### ISSUE THREAD

**Issue by MatthewClair** [LocalIdentity/PathOfBuilding#94]
Awakened gems are treated as if they are lv20 in the gem selection dropdown rather than their natural max of 5.  This can be reproduced quickly by testing Awakened Added Chaos Damage with a DoT spell.  It will give ~57% more damage over time rather than the expected ~12%.  Changing the "Default gem level" to 5 gives the expected result for Awakened Gems in the dropdown.

This has been reported on the main repo (https://github.com/Openarl/PathOfBuilding/issues/1814) but I figured it should be reported here as well.

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.5
