### ISSUE TITLE
Ensnaring Arrow Damage Debuff

### ISSUE THREAD

**Issue by ASprengle** [LocalIdentity/PathOfBuilding#95]
It would be great for the Ensnaring Arrow damage debuff ("Ensnared Enemies take #% increased Projectil Damage from Attack Hits") affect DPS. Thanks!

**Comment by LocalIdentity** [comment]
Added in 1.4.157.2

**Comment by ASprengle** [comment]
This seems to not have been working for at least the past few leagues. The last time I noticed it missing was 3.17 (sorry I hadn't reported until now).

**Comment by QuickStick123** [comment]
It works 
![image](https://user-images.githubusercontent.com/31533893/186784743-68a365d9-1490-4bd4-bd86-7a78c2f42047.png)

**Comment by ASprengle** [comment]
Ah nuts, I didn't see that part. Thank you!
